DATA:
  VIDEO_FILE: "/home/wgf/Downloads/datasets/water-level/2023-10-22/15-55-32.mp4"

METHOD:
  LEVEL_LINE: [500,780,800,900]
  LEVEL_ANGLE_THRESHOLD: 0.5 # in radians
  LEVEL_COORD_Y: 300
  LEVEL_LINE_DIFF: 5
  ENABLE_MOVING_AVERAGE: True
  MOVING_LEN: 10
  USE_GPU: True
  HOUGH_RHO: 1.0
  HOUGH_THETA: 0.017454
  HOUGH_MIN_LEN: 50
  HOUGH_MAX_LINE_GAP: 5
  HOUGH_MAX_LINES: 200
  CANNY_LOW_THRES: 100.0
  CANNY_HIGH_THRES: 200.0
  CANNY_APPERTURE: 3
  CANNY_L2: False

POST_PROCESS:
  POST_TEXT: "Water Level Warning"
  DRAW_LINE_WIDTH: 2
  DRAW_LINE_COLOR: [255,0,0]
  DRAW_LINE_COLOR_THRES: [0,0,255]
  TEXT_LINE_WIDTH: 2.6
  TEXT_FONT_SIZE: 2.0
  TEXT_LINE_COLOR: [255,0,0]
  TEXT_OFFSET_X: 800
  TEXT_OFFSET_Y: 50